# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from flashvsr.grpc.protos import flashvsr_pb2 as flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flashvsr/grpc/protos/flashvsr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlashVSRStub(object):
    """---------------------------------------------------------------------------
    FlashVSR gRPC Service

    Streaming video super-resolution (2× or 4×) using a diffusion-based model.
    Two usage patterns:

    Unary chunk-by-chunk flow (best for integration into existing pipelines):
    1. start_session  — allocates a fresh KV-cache for one video
    2. upscale_chunk  — send one chunk at a time (T=13 first, T=16 subsequent)
    3. end_session    — frees server-side state

    Bidirectional streaming (lowest latency, single RPC for the full video):
    upscale_video     — first message carries session config; server replies
    to each chunk immediately so the client can pipeline

    Health probe:
    get_status        — liveness/readiness check
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_status = channel.unary_unary(
                '/flashvsr.FlashVSR/get_status',
                request_serializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StatusRequest.SerializeToString,
                response_deserializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.start_session = channel.unary_unary(
                '/flashvsr.FlashVSR/start_session',
                request_serializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.end_session = channel.unary_unary(
                '/flashvsr.FlashVSR/end_session',
                request_serializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.EndSessionResponse.FromString,
                _registered_method=True)
        self.upscale_chunk = channel.unary_unary(
                '/flashvsr.FlashVSR/upscale_chunk',
                request_serializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkRequest.SerializeToString,
                response_deserializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkResponse.FromString,
                _registered_method=True)
        self.upscale_video = channel.stream_stream(
                '/flashvsr.FlashVSR/upscale_video',
                request_serializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkRequest.SerializeToString,
                response_deserializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkResponse.FromString,
                _registered_method=True)


class FlashVSRServicer(object):
    """---------------------------------------------------------------------------
    FlashVSR gRPC Service

    Streaming video super-resolution (2× or 4×) using a diffusion-based model.
    Two usage patterns:

    Unary chunk-by-chunk flow (best for integration into existing pipelines):
    1. start_session  — allocates a fresh KV-cache for one video
    2. upscale_chunk  — send one chunk at a time (T=13 first, T=16 subsequent)
    3. end_session    — frees server-side state

    Bidirectional streaming (lowest latency, single RPC for the full video):
    upscale_video     — first message carries session config; server replies
    to each chunk immediately so the client can pipeline

    Health probe:
    get_status        — liveness/readiness check
    ---------------------------------------------------------------------------

    """

    def get_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def end_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upscale_chunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upscale_video(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlashVSRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_status,
                    request_deserializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StatusRequest.FromString,
                    response_serializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StatusResponse.SerializeToString,
            ),
            'start_session': grpc.unary_unary_rpc_method_handler(
                    servicer.start_session,
                    request_deserializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StartSessionRequest.FromString,
                    response_serializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StartSessionResponse.SerializeToString,
            ),
            'end_session': grpc.unary_unary_rpc_method_handler(
                    servicer.end_session,
                    request_deserializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.EndSessionRequest.FromString,
                    response_serializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.EndSessionResponse.SerializeToString,
            ),
            'upscale_chunk': grpc.unary_unary_rpc_method_handler(
                    servicer.upscale_chunk,
                    request_deserializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkRequest.FromString,
                    response_serializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkResponse.SerializeToString,
            ),
            'upscale_video': grpc.stream_stream_rpc_method_handler(
                    servicer.upscale_video,
                    request_deserializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkRequest.FromString,
                    response_serializer=flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flashvsr.FlashVSR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flashvsr.FlashVSR', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlashVSR(object):
    """---------------------------------------------------------------------------
    FlashVSR gRPC Service

    Streaming video super-resolution (2× or 4×) using a diffusion-based model.
    Two usage patterns:

    Unary chunk-by-chunk flow (best for integration into existing pipelines):
    1. start_session  — allocates a fresh KV-cache for one video
    2. upscale_chunk  — send one chunk at a time (T=13 first, T=16 subsequent)
    3. end_session    — frees server-side state

    Bidirectional streaming (lowest latency, single RPC for the full video):
    upscale_video     — first message carries session config; server replies
    to each chunk immediately so the client can pipeline

    Health probe:
    get_status        — liveness/readiness check
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def get_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashvsr.FlashVSR/get_status',
            flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StatusRequest.SerializeToString,
            flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def start_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashvsr.FlashVSR/start_session',
            flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StartSessionRequest.SerializeToString,
            flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def end_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashvsr.FlashVSR/end_session',
            flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.EndSessionRequest.SerializeToString,
            flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def upscale_chunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flashvsr.FlashVSR/upscale_chunk',
            flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkRequest.SerializeToString,
            flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def upscale_video(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/flashvsr.FlashVSR/upscale_video',
            flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkRequest.SerializeToString,
            flashvsr_dot_grpc_dot_protos_dot_flashvsr__pb2.UpscaleChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
