# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from omnidreams.grpc.protos import common_pb2 as omnidreams_dot_grpc_dot_protos_dot_common__pb2
from omnidreams.grpc.protos import video_model_pb2 as omnidreams_dot_grpc_dot_protos_dot_video__model__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in omnidreams/grpc/protos/video_model_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorldModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.start_session = channel.unary_unary(
                '/omnidreams.video_model.WorldModelService/start_session',
                request_serializer=omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.SessionRequest.SerializeToString,
                response_deserializer=omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.SessionId.FromString,
                _registered_method=True)
        self.close_session = channel.unary_unary(
                '/omnidreams.video_model.WorldModelService/close_session',
                request_serializer=omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.SessionCloseRequest.SerializeToString,
                response_deserializer=omnidreams_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.render_video_chunk = channel.unary_unary(
                '/omnidreams.video_model.WorldModelService/render_video_chunk',
                request_serializer=omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.VideoChunkRequest.SerializeToString,
                response_deserializer=omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.VideoChunkReturn.FromString,
                _registered_method=True)
        self.get_version = channel.unary_unary(
                '/omnidreams.video_model.WorldModelService/get_version',
                request_serializer=omnidreams_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=omnidreams_dot_grpc_dot_protos_dot_common__pb2.VersionId.FromString,
                _registered_method=True)


class WorldModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def start_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def close_session(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def render_video_chunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorldModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'start_session': grpc.unary_unary_rpc_method_handler(
                    servicer.start_session,
                    request_deserializer=omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.SessionRequest.FromString,
                    response_serializer=omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.SessionId.SerializeToString,
            ),
            'close_session': grpc.unary_unary_rpc_method_handler(
                    servicer.close_session,
                    request_deserializer=omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.SessionCloseRequest.FromString,
                    response_serializer=omnidreams_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
            ),
            'render_video_chunk': grpc.unary_unary_rpc_method_handler(
                    servicer.render_video_chunk,
                    request_deserializer=omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.VideoChunkRequest.FromString,
                    response_serializer=omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.VideoChunkReturn.SerializeToString,
            ),
            'get_version': grpc.unary_unary_rpc_method_handler(
                    servicer.get_version,
                    request_deserializer=omnidreams_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
                    response_serializer=omnidreams_dot_grpc_dot_protos_dot_common__pb2.VersionId.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omnidreams.video_model.WorldModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omnidreams.video_model.WorldModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorldModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def start_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnidreams.video_model.WorldModelService/start_session',
            omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.SessionRequest.SerializeToString,
            omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.SessionId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def close_session(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnidreams.video_model.WorldModelService/close_session',
            omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.SessionCloseRequest.SerializeToString,
            omnidreams_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def render_video_chunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnidreams.video_model.WorldModelService/render_video_chunk',
            omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.VideoChunkRequest.SerializeToString,
            omnidreams_dot_grpc_dot_protos_dot_video__model__pb2.VideoChunkReturn.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omnidreams.video_model.WorldModelService/get_version',
            omnidreams_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
            omnidreams_dot_grpc_dot_protos_dot_common__pb2.VersionId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
